version: '3.8'
services:
  api:
    build: .
    container_name: we-connect-API
    restart: always
    environment:
      API_PORT: ":3000"
      MONGO_URL: "mongodb://mongo:27017"
      MONGO_DB_NAME: "financial-data-DB"
      MONGO_COLLECTION_NAME: "financial-data"
      CSV_FILE_PATH: "business-financial-data-mar-2022-quarter-csv.csv"
      LOAD_DATA: true
    ports:
      - "3000:3000"
    depends_on:
      - 'mongo'

  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
        - "27017:27017"